#!/bin/bash
## Docker Aliases
alias dcb='docker-compose build'
alias dcbw='docker-compose build workspace'
alias dcrm='docker rm'
alias dcu='docker-compose up'
alias di='docker images'
alias dirm='docker image rm'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias drmc='docker rm $(docker ps -aq)'
alias drmi='docker rmi $(docker images -aq)'
alias dsdf='docker system df'
alias watchlog='docker logs -f laradock_php-fpm_1'
alias reloadphp='docker-compose up -d --force-recreate --build nginx'
